### ISSUE TITLE
Implement translation support

### ISSUE THREAD

**Issue by kuragehimekurara1** [sharkwouter/oceanpop#59]
I would like to translate oceanpop into Japanese, can I do it?  If you can translate it, I would like to translate it.

**Comment by sharkwouter** [comment]
Thanks for the request, it's appreciated. At the moment OceanPop does not support translations, though, but I am interested in implementing it. Can I write you when this is possible?

**Comment by kuragehimekurara1** [comment]
I understand!  Please let us know by email or this issue when translation is possible!  Please let me know when it will be possible later!

**Comment by sharkwouter** [comment]
Will do! Thanks!

**Comment by kuragehimekurara1** [comment]
It's been four months since then, what happened?

**Comment by sharkwouter** [comment]
I'm doing a small release now, so I can make this available to some more people. Unfortunately, I did not get to this one yet, since I'm not quite sure how to do this yet and it's not very high on my list of things I'd like to work on.

If someone would like to implement translation support, I'd love to see a PR.

**Comment by sharkwouter** [comment]
@kuragehimekurara1 I finally managed to find a way to implement translation support. There are not many internationalization libraries that are not GPL licensed unfortunately, but I found one. It's even quite easy to make work for multiple platforms. I'm trying to figure out how I could make it work on PSP now. Will look into Windows later. Linux already works.

**Comment by sharkwouter** [comment]
I also added some info on how to add a new translation to CONTRIBUTING.md.

**Comment by kuragehimekurara1** [comment]
OK.
It may take a while because there are many other things I need to do,We will translate it soon, so please wait.

**Comment by sharkwouter** [comment]
Cool, looking forward to it. No rush, though.

**Comment by sharkwouter** [comment]
I'm going to close this one, because translation support is there now. We do need more translations, though.

**Comment by sharkwouter** [comment]
@kuragehimekurara1 I would like to release Minigalaxy 2.0 soon. Are you still planning to do the translation? I'd be willing to wait so you can get things working. You could download the ready made build [here](https://github.com/sharkwouter/oceanpop/actions/runs/12071951107) and create the file `assets/languages/ja.po` with a tool like poedit. Then you can just run the binary on a system which has the language set to Japanese to test it.
